# Generated by Django 2.1.1 on 2018-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0002_auto_20181016_2027'),
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctoun', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=None, to='df_goods.GoodsInfo')),
                ('user', models.ForeignKey(on_delete=None, to='df_user.UserInfo')),
            ],
        ),
    ]
